### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nisrulz** [nisrulz/android-spacex-app#4]
- [ ] [Material Docs](https://squidfunk.github.io/mkdocs-material/)
- [ ] Github Actions for building APK/Releases
- [ ] Github Actions for running Unit Tests
- [ ] Changelog Generation from Commits
- [ ] Pagination
- [ ] Analytics Module
- [ ] Extract Networking code into its own module i.e `network-ktor`, `network-retrofit`
- [ ] Extract Storage code into its own module i.e `storage-room`, `storage-cache`
